# Generated by Django 6.0.4 on 2026-04-28 04:51

import django.utils.timezone
from django.db import migrations, models

import siwe_django.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="EthereumUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Designates that this user has all permissions without "
                            "explicitly assigning them."
                        ),
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "ethereum_address",
                    models.CharField(
                        max_length=42,
                        unique=True,
                        validators=[siwe_django.models.validate_ethereum_address],
                    ),
                ),
                ("chain_id", models.PositiveIntegerField(default=1)),
                ("ens_name", models.CharField(blank=True, max_length=255)),
                ("ens_avatar", models.URLField(blank=True, max_length=1024)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="siwe_ethereum_users",
                        related_query_name="siwe_ethereum_user",
                        to="auth.group",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="siwe_ethereum_users",
                        related_query_name="siwe_ethereum_user",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ethereum user",
                "verbose_name_plural": "Ethereum users",
            },
        ),
        migrations.CreateModel(
            name="SiweNonce",
            fields=[
                (
                    "nonce",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("session_key", models.CharField(blank=True, max_length=64)),
                ("domain", models.CharField(blank=True, max_length=255)),
                ("uri", models.URLField(blank=True, max_length=2048)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["expires_at"],
                        name="siwe_django_expires_b4a7b7_idx",
                    ),
                    models.Index(
                        fields=["session_key"],
                        name="siwe_django_session_b77bc9_idx",
                    ),
                    models.Index(
                        fields=["consumed_at"],
                        name="siwe_django_consume_a68a6d_idx",
                    ),
                ],
            },
        ),
    ]
