# Generated by Django 6.0.4 on 2026-04-28 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import siwe_django.models


class Migration(migrations.Migration):
    dependencies = [
        ("siwe_django", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiweWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=42,
                        validators=[siwe_django.models.validate_ethereum_address],
                    ),
                ),
                ("chain_id", models.PositiveIntegerField()),
                ("caip10", models.CharField(editable=False, max_length=128)),
                ("ens_name", models.CharField(blank=True, max_length=255)),
                ("ens_avatar", models.URLField(blank=True, max_length=1024)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="siwe_wallets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "chain_id", "address"],
                "indexes": [
                    models.Index(
                        fields=["user", "chain_id"],
                        name="siwe_django_user_id_b754a4_idx",
                    ),
                    models.Index(
                        fields=["caip10"], name="siwe_django_caip10_5c51d0_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chain_id", "address"),
                        name="siwe_wallet_unique_chain_address",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("user",),
                        name="siwe_wallet_one_primary_per_user",
                    ),
                ],
            },
        ),
    ]
