# Generated by Django 6.0.4 on 2026-04-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siwe_django", "0002_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="ethereumuser",
            name="ens_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ethereumuser",
            name="ens_header",
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="ethereumuser",
            name="ens_records",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="ethereumuser",
            name="followers_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ethereumuser",
            name="following_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ethereumuser",
            name="identity_avatar",
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="ethereumuser",
            name="identity_display_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="ethereumuser",
            name="identity_profile",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="ethereumuser",
            name="identity_url",
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="siwewallet",
            name="ens_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="siwewallet",
            name="ens_header",
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="siwewallet",
            name="ens_records",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="siwewallet",
            name="followers_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="siwewallet",
            name="following_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="siwewallet",
            name="identity_avatar",
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="siwewallet",
            name="identity_display_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="siwewallet",
            name="identity_profile",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="siwewallet",
            name="identity_url",
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
