# Generated by Django 6.0.4 on 2026-04-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siwe_django", "0003_identity_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="siwenonce",
            name="not_before",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siwenonce",
            name="request_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="siwenonce",
            name="resources",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
