# Generated by Django 6.0.4 on 2026-04-28 08:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siwe_django", "0004_eip4361_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiweAuthEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("nonce_issued", "Nonce issued"),
                            ("verify_succeeded", "Verify succeeded"),
                            ("verify_failed", "Verify failed"),
                            ("link_succeeded", "Link succeeded"),
                            ("link_failed", "Link failed"),
                            ("unlink", "Wallet unlinked"),
                            ("logout", "Logout"),
                        ],
                        max_length=32,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=42)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("success", models.BooleanField(default=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="siwe_auth_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["address", "timestamp"],
                        name="siwe_django_address_804459_idx",
                    ),
                    models.Index(
                        fields=["event", "timestamp"],
                        name="siwe_django_event_5e1203_idx",
                    ),
                ],
            },
        ),
    ]
